LEAF_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include ../leaf.mk

POSITIVE_SILICA := \
	heap_empty_and_singleton.silica \
	heap_push_pop_order.silica \
	heap_duplicates.silica \
	heap_meld.silica \
	heap_from_list.silica \
	heap_persistence.silica \
	heap_large_runs.silica \
	heap_generic_payloads.silica \
	heap_trait_dispatch.silica \
	heap_validate.silica \
	pq_empty.silica \
	pq_push_pop_lexicographic.silica \
	pq_duplicates.silica \
	pq_meld.silica \
	pq_from_entries.silica \
	pq_persistence.silica \
	pq_large_runs.silica \
	pq_generic_payloads.silica \
	pq_trait_dispatch.silica \
	pq_validate.silica
