LEAF_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include ../leaf.mk

POSITIVE_SILICA := \
	gcsr_directed_freeze.silica \
	gcsr_snapshot_isolation.silica \
	gcsr_undirected.silica \
	gcsr_weighted.silica \
	gcsr_validate.silica \
	gcsr_equivalence_large.silica \
	gcsr_generic_payloads.silica \
	gcsr_record_edge_data.silica
