LEAF_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include ../leaf.mk

POSITIVE_SILICA := \
	gl_directed_vertices.silica \
	gl_directed_add_edge.silica \
	gl_directed_remove_edge.silica \
	gl_directed_payloads.silica \
	gl_directed_folds_reachable.silica \
	gl_undirected_symmetry.silica \
	gl_unit_edges.silica \
	gl_weighted_directed.silica \
	gl_weighted_undirected.silica \
	gl_persistence_sharing.silica \
	gl_validate.silica \
	gl_large_oracle.silica \
	gl_generic_payloads.silica \
	gl_record_edge_data.silica \
	gl_tuple_node_ids.silica
