LEAF_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include ../leaf.mk

POSITIVE_SILICA := \
	gc_directed_trait.silica \
	gc_undirected_trait.silica \
	gc_undirected_trait_weighted.silica \
	gc_weighted_trait.silica \
	gc_weighted_trait_undirected.silica \
	gc_trait_generic_payloads.silica \
	gc_csr_directed_trait.silica \
	gc_csr_undirected_trait.silica \
	gc_csr_weighted_trait.silica \
	gc_csr_weighted_undirected_trait.silica \
	gc_dense_directed_trait.silica \
	gc_dense_undirected_trait.silica \
	gc_dense_weighted_trait.silica \
	gc_dense_weighted_undirected_trait.silica \
	gc_trait_record_edge_data.silica \
	trait_placeholder_result_dispatch.silica
