LEAF_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include ../leaf.mk

POSITIVE_SILICA := \
	ordered_map_empty_public.silica \
	ordered_map_trait_dispatch.silica \
	ordered_map_find_value_linear.silica \
	wbt_map_get_insert.silica \
	ordered_map_insert_replace.silica \
	ordered_map_delete_absent.silica \
	ordered_map_from_sorted.silica \
	ordered_map_not_found_status.silica \
	ordered_map_compare_value_not_called.silica \
	ordered_map_persistence.silica \
	ordered_map_string_example.silica \
	ordered_set_empty_public.silica \
	ordered_set_trait_dispatch.silica \
	wbt_set_empty_insert.silica \
	ordered_set_duplicate_insert.silica \
	ordered_set_invalid_comparator.silica \
	ordered_set_from_sorted.silica \
	ordered_set_persistence.silica \
	ordered_set_string_example.silica
