=== standard_data_structures: compile stdlib data structures once ===
Resuming compile order; units left: 
4
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_set.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_set
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
3
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_map.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_map
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
2
Parsing 
lib/OrderedMap.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
lib/OrderedMap.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling OrderedMap
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
1
Parsing 
lib/OrderedSet.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Compiling 
lib/OrderedSet.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling OrderedSet
Compilation complete.
Assembling lib/OrderedMap.sams -> lib/OrderedMap.o
Assembling lib/OrderedSet.sams -> lib/OrderedSet.o
Assembling lib/wbt_map.sams -> lib/wbt_map.o
Assembling lib/wbt_set.sams -> lib/wbt_set.o
✅ standard_data_structures: reusing .stdlib_cache/lib/*.o for every trial
=== standard_data_structures_phase1/compiler_substrate ===
standard_data_structures_phase1/compiler_substrate/regenerating silica.config...
standard_data_structures_phase1/compiler_substrate/positive-integrate: starting...
Compiling with silica-compiler...
Resuming compile order; units left: 
47
Parsing 
lib/MiniOrderedSet.silica...
  Lexing...
  Parsing...
Compiling 
lib/MiniOrderedSet.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling MiniOrderedSet
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
46
Parsing 
lib/ScaleTrait.silica...
  Lexing...
  Parsing...
Compiling 
lib/ScaleTrait.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling ScaleTrait
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
45
Parsing 
lib/SizeTrait.silica...
  Lexing...
  Parsing...
Compiling 
lib/SizeTrait.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling SizeTrait
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
44
Parsing 
lib/StubGraphDirected.silica...
  Lexing...
  Parsing...
Compiling 
lib/StubGraphDirected.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling StubGraphDirected
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
43
Parsing 
lib/StubGraphUndirected.silica...
  Lexing...
  Parsing...
Compiling 
lib/StubGraphUndirected.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling StubGraphUndirected
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
42
Parsing 
lib/StubGraphWeighted.silica...
  Lexing...
  Parsing...
Compiling 
lib/StubGraphWeighted.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling StubGraphWeighted
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
41
Parsing 
lib/StubHeap.silica...
  Lexing...
  Parsing...
Compiling 
lib/StubHeap.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling StubHeap
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
40
Parsing 
lib/StubHeapMax.silica...
  Lexing...
  Parsing...
Compiling 
lib/StubHeapMax.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling StubHeapMax
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
39
Parsing 
lib/StubPriorityQueue.silica...
  Lexing...
  Parsing...
Compiling 
lib/StubPriorityQueue.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling StubPriorityQueue
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
38
Parsing 
lib/StubTreeRose.silica...
  Lexing...
  Parsing...
Compiling 
lib/StubTreeRose.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling StubTreeRose
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
37
Parsing 
lib/StubWbtMap.silica...
  Lexing...
  Parsing...
Compiling 
lib/StubWbtMap.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling StubWbtMap
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
36
Parsing 
lib/StubWbtSet.silica...
  Lexing...
  Parsing...
Compiling 
lib/StubWbtSet.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling StubWbtSet
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
35
Parsing 
lib/TagTrait.silica...
  Lexing...
  Parsing...
Compiling 
lib/TagTrait.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling TagTrait
Unit compiled; exiting to reclaim memory before next unit...
  (reclaiming memory; continuing next unit)
Resuming compile order; units left: 
34
Parsing 
lib/type_interner.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/OrderedMap.silica...
  Lexing...
  Parsing...
Compiling 
lib/type_interner.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
❌❌ standard_data_structures_phase1/compiler_substrate integrate failed (no .integrate_counts)
=== standard_data_structures_phase1/wbt_core ===
standard_data_structures_phase1/wbt_core/positive-integrate: starting...
Compiling with silica-compiler (one trial per process)...
standard_data_structures_phase1/wbt_core/compiling 10 lib unit(s) once for this integrate
Resuming compile order; units left: 
10
Parsing 
lib/wbt_trial_balance.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_balance.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_balance
Unit compiled; exiting to reclaim memory before next unit...
  standard_data_structures_phase1/wbt_core/reclaim; units left in lib units: 9/10
Resuming compile order; units left: 
9
Parsing 
lib/wbt_trial_delete_i64.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_delete_i64.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_delete_i64
Unit compiled; exiting to reclaim memory before next unit...
  standard_data_structures_phase1/wbt_core/reclaim; units left in lib units: 8/10
Resuming compile order; units left: 
8
Parsing 
lib/wbt_trial_delete_map_i64.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_delete_map_i64.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_delete_map_i64
Unit compiled; exiting to reclaim memory before next unit...
  standard_data_structures_phase1/wbt_core/reclaim; units left in lib units: 7/10
Resuming compile order; units left: 
7
Parsing 
lib/wbt_trial_fixture.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_fixture.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_fixture
Unit compiled; exiting to reclaim memory before next unit...
  standard_data_structures_phase1/wbt_core/reclaim; units left in lib units: 6/10
Resuming compile order; units left: 
6
Parsing 
lib/wbt_trial_i64.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_i64.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_i64
Unit compiled; exiting to reclaim memory before next unit...
  standard_data_structures_phase1/wbt_core/reclaim; units left in lib units: 5/10
Resuming compile order; units left: 
5
Parsing 
lib/wbt_trial_insert_i64.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_insert_i64.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_insert_i64
Unit compiled; exiting to reclaim memory before next unit...
  standard_data_structures_phase1/wbt_core/reclaim; units left in lib units: 4/10
Resuming compile order; units left: 
4
Parsing 
lib/wbt_trial_insert_map_i64.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_insert_map_i64.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_insert_map_i64
Unit compiled; exiting to reclaim memory before next unit...
  standard_data_structures_phase1/wbt_core/reclaim; units left in lib units: 3/10
Resuming compile order; units left: 
3
Parsing 
lib/wbt_trial_oracle_i64.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_oracle_i64.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_oracle_i64
Unit compiled; exiting to reclaim memory before next unit...
  standard_data_structures_phase1/wbt_core/reclaim; units left in lib units: 2/10
Resuming compile order; units left: 
2
Parsing 
lib/wbt_trial_shape_i64.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_shape_i64.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_shape_i64
Unit compiled; exiting to reclaim memory before next unit...
  standard_data_structures_phase1/wbt_core/reclaim; units left in lib units: 1/10
Resuming compile order; units left: 
1
Parsing 
lib/wbt_trial_trace_i64.silica...
  Lexing...
  Parsing...
Compiling 
lib/wbt_trial_trace_i64.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_trial_trace_i64
Compilation complete.
standard_data_structures_phase1/wbt_core/lib units compiled; later trials will reuse their .o files
standard_data_structures_phase1/wbt_core/per-trial compile: 80 trial(s); each trial reuses lib .o files
standard_data_structures_phase1/wbt_core/trial 1/80: smoke_harness_ready.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
smoke_harness_ready.silica...
  Lexing...
  Parsing...
Compiling 
smoke_harness_ready.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling smoke_harness_ready
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 1/80: smoke_harness_ready.silica done
standard_data_structures_phase1/wbt_core/trial 2/80: wbt_balance_boundaries.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_balance_boundaries.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Compiling 
wbt_balance_boundaries.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_balance_boundaries
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 2/80: wbt_balance_boundaries.silica done
standard_data_structures_phase1/wbt_core/trial 3/80: wbt_constructor_ordering_bundle.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_constructor_ordering_bundle.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Compiling 
wbt_constructor_ordering_bundle.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_constructor_ordering_bundle
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 3/80: wbt_constructor_ordering_bundle.silica done
standard_data_structures_phase1/wbt_core/trial 4/80: wbt_empty_representation.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_empty_representation.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_empty_representation.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_empty_representation
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 4/80: wbt_empty_representation.silica done
standard_data_structures_phase1/wbt_core/trial 5/80: wbt_fold_ascending.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_fold_ascending.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_fixture.silica...
  Lexing...
  Parsing...
Compiling 
wbt_fold_ascending.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_fold_ascending
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 5/80: wbt_fold_ascending.silica done
standard_data_structures_phase1/wbt_core/trial 6/80: wbt_from_sorted_empty.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_empty.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_empty.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_empty
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 6/80: wbt_from_sorted_empty.silica done
standard_data_structures_phase1/wbt_core/trial 7/80: wbt_from_sorted_singleton.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_singleton.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_singleton.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_singleton
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 7/80: wbt_from_sorted_singleton.silica done
standard_data_structures_phase1/wbt_core/trial 8/80: wbt_from_sorted_two.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_two.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_two.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_two
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 8/80: wbt_from_sorted_two.silica done
standard_data_structures_phase1/wbt_core/trial 9/80: wbt_from_sorted_valid_invalid.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_valid_invalid.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_valid_invalid.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_valid_invalid
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 9/80: wbt_from_sorted_valid_invalid.silica done
standard_data_structures_phase1/wbt_core/trial 10/80: wbt_from_sorted_count_mismatch.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_count_mismatch.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_count_mismatch.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_count_mismatch
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 10/80: wbt_from_sorted_count_mismatch.silica done
standard_data_structures_phase1/wbt_core/trial 11/80: wbt_from_sorted_map_invalid_two.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_map_invalid_two.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_map_invalid_two.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_map_invalid_two
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 11/80: wbt_from_sorted_map_invalid_two.silica done
standard_data_structures_phase1/wbt_core/trial 12/80: wbt_from_sorted_shape.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_shape.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_i64.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_shape_i64.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_shape.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_shape
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 12/80: wbt_from_sorted_shape.silica done
standard_data_structures_phase1/wbt_core/trial 13/80: wbt_from_sorted_shape_large.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_shape_large.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_shape_i64.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_shape_large.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_shape_large
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 13/80: wbt_from_sorted_shape_large.silica done
standard_data_structures_phase1/wbt_core/trial 14/80: wbt_from_sorted_set_map.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_set_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_i64.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_shape_i64.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_set_map.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_set_map
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 14/80: wbt_from_sorted_set_map.silica done
standard_data_structures_phase1/wbt_core/trial 15/80: wbt_from_sorted_ten_plus.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_ten_plus.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_i64.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_ten_plus.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_ten_plus
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 15/80: wbt_from_sorted_ten_plus.silica done
standard_data_structures_phase1/wbt_core/trial 16/80: wbt_from_sorted_linear.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_linear.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_i64.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_shape_i64.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_linear.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_linear
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 16/80: wbt_from_sorted_linear.silica done
standard_data_structures_phase1/wbt_core/trial 17/80: wbt_from_sorted_persistence.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_from_sorted_persistence.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_from_sorted_persistence.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_from_sorted_persistence
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 17/80: wbt_from_sorted_persistence.silica done
standard_data_structures_phase1/wbt_core/trial 18/80: wbt_generic_payload_shapes.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_generic_payload_shapes.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_generic_payload_shapes.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_generic_payload_shapes
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 18/80: wbt_generic_payload_shapes.silica done
standard_data_structures_phase1/wbt_core/trial 19/80: wbt_generic_tuple_map_empty.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_generic_tuple_map_empty.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_generic_tuple_map_empty.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_generic_tuple_map_empty
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 19/80: wbt_generic_tuple_map_empty.silica done
standard_data_structures_phase1/wbt_core/trial 20/80: wbt_minimum_maximum.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_minimum_maximum.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_fixture.silica...
  Lexing...
  Parsing...
Compiling 
wbt_minimum_maximum.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_minimum_maximum
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 20/80: wbt_minimum_maximum.silica done
standard_data_structures_phase1/wbt_core/trial 21/80: wbt_read_only_alloc_free.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_read_only_alloc_free.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_fixture.silica...
  Lexing...
  Parsing...
Compiling 
wbt_read_only_alloc_free.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_read_only_alloc_free
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 21/80: wbt_read_only_alloc_free.silica done
standard_data_structures_phase1/wbt_core/trial 22/80: wbt_read_only_empty.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_read_only_empty.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_read_only_empty.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_read_only_empty
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 22/80: wbt_read_only_empty.silica done
standard_data_structures_phase1/wbt_core/trial 23/80: wbt_rebalance_adversarial.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_rebalance_adversarial.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_fixture.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_balance.silica...
  Lexing...
  Parsing...
Compiling 
wbt_rebalance_adversarial.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_rebalance_adversarial
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 23/80: wbt_rebalance_adversarial.silica done
standard_data_structures_phase1/wbt_core/trial 24/80: wbt_representation_specializations.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_representation_specializations.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Compiling 
wbt_representation_specializations.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_representation_specializations
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 24/80: wbt_representation_specializations.silica done
standard_data_structures_phase1/wbt_core/trial 25/80: wbt_representation_string_specialization.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_representation_string_specialization.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Compiling 
wbt_representation_string_specialization.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_representation_string_specialization
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 25/80: wbt_representation_string_specialization.silica done
standard_data_structures_phase1/wbt_core/trial 26/80: wbt_rotation_double_left.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_rotation_double_left.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_fixture.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_balance.silica...
  Lexing...
  Parsing...
Compiling 
wbt_rotation_double_left.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_rotation_double_left
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 26/80: wbt_rotation_double_left.silica done
standard_data_structures_phase1/wbt_core/trial 27/80: wbt_rotation_double_right.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_rotation_double_right.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_map.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_fixture.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_trial_balance.silica...
  Lexing...
  Parsing...
Compiling 
wbt_rotation_double_right.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
Finished compiling wbt_rotation_double_right
Compilation complete.
standard_data_structures_phase1/wbt_core/trial 27/80: wbt_rotation_double_right.silica done
standard_data_structures_phase1/wbt_core/trial 28/80: wbt_rotation_gamma_equality.silica (trial unit only)...
Resuming compile order; units left: 
1
Parsing 
wbt_rotation_gamma_equality.silica...
  Lexing...
  Parsing...
Parsing 
lib/wbt_set.silica...
  Lexing...
  Parsing...
Compiling 
wbt_rotation_gamma_equality.silica...
  Module checking...
  FFI metadata...
  FFI placement...
  Type checking...
  FFI ABI...
  FFI taint...
  Trait checking...
  Effect checking...
  Generating SIR...
  Emitting...
