LEAF_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include ../leaf.mk

POSITIVE_SILICA := \
	gd_directed_updates.silica \
	gd_undirected.silica \
	gd_weighted.silica \
	gd_universe.silica \
	gd_validate.silica \
	gd_equivalence.silica \
	gd_generic_payloads.silica \
	gd_record_edge_data.silica
