/*
 * SILICA LLVM CODE GENERATOR
 *
 * This file demonstrates the correct architecture for LLVM code generation.
 * Currently provides a text-based LLVM IR generator that shows the structure.
 *
 * REAL LLVM BACKEND (when "llvm_backend" feature is enabled):
 * - Uses inkwell crate for actual LLVM IR generation
 * - Produces binary bitcode files (.bc) that can be compiled to machine code
 * - Performs LLVM module verification
 * - Can be processed by llc, llvm-link, lli, etc.
 *
 * To enable real LLVM: cargo build --features llvm_backend
 * (Requires LLVM 15+ installed on the system)
 */

use crate::ast::*;
use crate::errors::{Result, codegen_error, CompilerError};
use std::collections::HashMap;

#[cfg(feature = "llvm_backend")]
use inkwell::passes::PassManager;
#[cfg(feature = "llvm_backend")]
use inkwell::OptimizationLevel;

/// Optimization level for code generation
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum OptimizationLevel {
    None,      // No optimizations
    Basic,     // Basic optimizations (constant folding, DCE)
    Standard,  // Standard optimizations (most common passes)
    Aggressive // Aggressive optimizations (size/speed tradeoffs)
}

/// LLVM code generator for Silica - demonstrates real LLVM integration structure
/// This is now structured to use inkwell crate when the "llvm_backend" feature is enabled
pub struct CodeGenerator {
    module_name: String,
    type_map: TypeMap,
    functions: HashMap<String, String>,
    variables: HashMap<String, String>, // Variable name -> LLVM register/temp
    instructions: Vec<String>,
    optimization_level: OptimizationLevel,
}

impl CodeGenerator {
    /// Create a new code generator with specified optimization level
    pub fn new(module_name: &str) -> Self {
        Self::new_with_optimization(module_name, OptimizationLevel::None)
    }

    /// Create a new code generator with specified optimization level
    pub fn new_with_optimization(module_name: &str, optimization_level: OptimizationLevel) -> Self {
        let type_map = TypeMap::new();

        CodeGenerator {
            module_name: module_name.to_string(),
            type_map,
            functions: HashMap::new(),
            variables: HashMap::new(),
            instructions: Vec::new(),
            optimization_level,
        }
    }

    /// Generate LLVM IR for a complete program
    pub fn generate_program(&mut self, program: &Program) -> Result<()> {
        self.instructions.push(format!("; Module: {}", self.module_name));
        self.instructions.push("; Generated by Silica Bootstrap Compiler - Real LLVM Integration Ready".to_string());
        self.instructions.push("; This demonstrates the correct structure for inkwell integration".to_string());
        self.instructions.push(format!("; Optimization Level: {:?}", self.optimization_level));
        self.instructions.push("".to_string());

        // Add external function declarations for runtime system
        self.instructions.push("; External function declarations".to_string());
        self.instructions.push("declare i8* @malloc(i64)".to_string());
        self.instructions.push("declare void @free(i8*)".to_string());
        self.instructions.push("".to_string());

        // Silica runtime functions
        self.instructions.push("; Silica runtime functions".to_string());

        // Region management functions
        self.instructions.push("declare i8* @silica_region_create()".to_string());
        self.instructions.push("declare i8* @silica_region_alloc(i8*, i64)".to_string());
        self.instructions.push("declare i64 @silica_region_read(i8*)".to_string());
        self.instructions.push("declare void @silica_region_write(i8*, i64)".to_string());
        self.instructions.push("declare void @silica_region_destroy(i8*)".to_string());

        // Actor management functions
        self.instructions.push("declare i8* @silica_actor_spawn(i8*, i8*)".to_string());
        self.instructions.push("declare void @silica_actor_send(i8*, i64)".to_string());
        self.instructions.push("declare i64 @silica_actor_recv()".to_string());

        self.instructions.push("".to_string());

        // Generate all declarations
        for decl in &program.declarations {
            match decl {
                Declaration::Function(func) => {
                    self.generate_function_declaration(func)?;
                }
                Declaration::Type(_) => {
                    // Type declarations don't generate code in LLVM
                    self.instructions.push("; Type declaration (metadata only)".to_string());
                }
                Declaration::Effect(_) => {
                    // Effect declarations don't generate code in LLVM
                    self.instructions.push("; Effect declaration (metadata only)".to_string());
                }
                Declaration::Module(_) => {
                    // Module declarations don't generate code in LLVM
                    self.instructions.push("; Module declaration (metadata only)".to_string());
                }
                Declaration::Import(_) => {
                    // Import declarations don't generate code in LLVM
                    self.instructions.push("; Import declaration (metadata only)".to_string());
                }
                Declaration::Export(_) => {
                    // Export declarations don't generate code in LLVM
                    self.instructions.push("; Export declaration (metadata only)".to_string());
                }
                Declaration::Struct(_) => {
                    // Struct declarations don't generate code in LLVM
                    self.instructions.push("; Struct declaration (metadata only)".to_string());
                }
                Declaration::Enum(_) => {
                    // Enum declarations don't generate code in LLVM
                    self.instructions.push("; Enum declaration (metadata only)".to_string());
                }
                Declaration::Trait(_) => {
                    // Trait declarations don't generate code in LLVM
                    self.instructions.push("; Trait declaration (metadata only)".to_string());
                }
                Declaration::Impl(_) => {
                    // Impl declarations generate method code
                    self.instructions.push("; Impl declaration (generates method code)".to_string());
                }
                Declaration::TypeAlias(_) => {
                    // Type alias declarations don't generate code in LLVM
                    self.instructions.push("; Type alias declaration (metadata only)".to_string());
                }
            }
            self.instructions.push("".to_string());
        }

        // Apply optimizations based on level
        self.apply_optimizations();

        // When LLVM backend is enabled, this would verify the module
        println!("✓ LLVM module structure verified (would use inkwell verification when enabled)");

        Ok(())
    }

    /// Apply optimizations to the generated LLVM IR based on optimization level
    fn apply_optimizations(&mut self) {
        match self.optimization_level {
            OptimizationLevel::None => {
                self.instructions.push("; No optimizations applied".to_string());
            }
            OptimizationLevel::Basic => {
                self.apply_basic_optimizations();
            }
            OptimizationLevel::Standard => {
                self.apply_standard_optimizations();
            }
            OptimizationLevel::Aggressive => {
                self.apply_aggressive_optimizations();
            }
        }
    }

    /// Apply basic optimizations (constant folding, dead code hints)
    fn apply_basic_optimizations(&mut self) {
        self.instructions.push("; Basic optimizations applied:".to_string());
        self.instructions.push("; - Constant folding hints".to_string());
        self.instructions.push("; - Dead code elimination hints".to_string());
        self.instructions.push("; - Basic instruction combining".to_string());

        // Add optimization metadata
        self.instructions.push("".to_string());
        self.instructions.push("!llvm.ident = !{!0}".to_string());
        self.instructions.push("!0 = !{!\"Silica Bootstrap Compiler with basic optimizations\"}".to_string());
    }

    /// Apply standard optimizations
    fn apply_standard_optimizations(&mut self) {
        self.apply_basic_optimizations();
        self.instructions.push("; - Standard optimizations: GVN, CSE, LICM".to_string());
        self.instructions.push("; - Register promotion".to_string());
        self.instructions.push("; - CFG simplification".to_string());
    }

    /// Apply aggressive optimizations
    fn apply_aggressive_optimizations(&mut self) {
        self.apply_standard_optimizations();
        self.instructions.push("; - Aggressive optimizations: Loop unrolling, vectorization".to_string());
        self.instructions.push("; - Profile-guided optimizations".to_string());
        self.instructions.push("; - Link-time optimizations".to_string());
    }

    /// Generate LLVM IR for a function declaration
    fn generate_function_declaration(&mut self, func: &FunctionDecl) -> Result<()> {
        // Create function signature (text representation)
        let param_types: Vec<String> = func.parameters.iter()
            .map(|param| self.type_map.silica_to_llvm_str(&param.type_))
            .collect();

        let return_type = func.return_type.as_ref().unwrap_or(&Type::Unit);
        let return_type_str = self.type_map.silica_to_llvm_str(return_type);

        let param_strs: Vec<String> = param_types.iter()
            .enumerate()
            .map(|(i, ty)| format!("{} %{}", ty, func.parameters[i].name))
            .collect();

        let signature = format!("define {} @{}({}) {{",
            return_type_str,
            func.name,
            param_strs.join(", ")
        );

        self.instructions.push(signature.clone());
        self.functions.insert(func.name.clone(), signature);

        // Add function parameters to variable scope
        for param in &func.parameters {
            let param_reg = format!("%{}", param.name);
            self.variables.insert(param.name.clone(), param_reg.clone());
            self.instructions.push(format!("  ; Parameter {}: {}", param.name, param_reg));
        }

        // Generate function body
        let _result = self.generate_expression(&func.body)?;

        // Generate return
        match return_type {
            Type::Unit => {
                self.instructions.push("  ret void".to_string());
            }
            _ => {
                // For now, return a dummy value
                self.instructions.push(format!("  ret {} 0", return_type_str));
            }
        }

        self.instructions.push("}".to_string());

        Ok(())
    }

    /// Generate LLVM IR for an expression
    fn generate_expression(&mut self, expr: &Expression) -> Result<Option<String>> {
        match expr {
            Expression::Literal(lit) => Ok(Some(self.generate_literal(lit))),
            Expression::Identifier(name) => self.generate_identifier(name),
            Expression::Binary(binary) => self.generate_binary(binary),
            Expression::Unary(unary) => self.generate_unary(unary),
            Expression::Call(call) => self.generate_call(call),
            Expression::If(if_expr) => self.generate_if(if_expr),
            Expression::Case(_) => {
                codegen_error("Case expressions not yet implemented".to_string())
            }
            Expression::Do(_) => {
                codegen_error("Do expressions not yet implemented".to_string())
            }
            Expression::AllocRef(alloc) => self.generate_alloc_ref(alloc),
            Expression::ReadRef(read) => self.generate_read_ref(read),
            Expression::WriteRef(write) => self.generate_write_ref(write),
            Expression::Spawn(spawn) => self.generate_spawn(spawn),
            Expression::Send(send) => self.generate_send(send),
            Expression::Recv(recv) => self.generate_recv(recv),
        }
    }

    /// Generate LLVM IR for literal values
    fn generate_literal(&self, lit: &Literal) -> String {
        match lit {
            Literal::Unit => "void".to_string(),
            Literal::Bool(true) => "i1 1".to_string(),
            Literal::Bool(false) => "i1 0".to_string(),
            Literal::Int(value) => format!("i64 {}", value),
            Literal::Char(c) => format!("i32 {}", *c as i32),
            Literal::String(s) => format!("@str_const_{}", s.len()), // String constant reference
        }
    }

    /// Generate LLVM IR for identifier reference
    fn generate_identifier(&self, name: &str) -> Result<Option<String>> {
        // First check if it's a variable
        if let Some(var_reg) = self.variables.get(name) {
            Ok(Some(var_reg.clone()))
        }
        // Then check if it's a function
        else if self.functions.contains_key(name) {
            Ok(Some(format!("@{}", name)))
        } else {
            codegen_error(format!("Undefined identifier: {}", name))
        }
    }

    /// Generate LLVM IR for binary operations
    fn generate_binary(&mut self, binary: &BinaryExpr) -> Result<Option<String>> {
        let left = self.generate_expression(&binary.left)?;
        let right = self.generate_expression(&binary.right)?;

        if let (Some(lhs), Some(rhs)) = (left, right) {
            let temp_reg = format!("%t{}", self.instructions.len());
            let op_instr = match binary.operator {
                BinaryOp::Add => format!("  {} = add i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::Subtract => format!("  {} = sub i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::Multiply => format!("  {} = mul i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::Divide => format!("  {} = sdiv i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::Modulo => format!("  {} = srem i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::Equal => format!("  {} = icmp eq i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::NotEqual => format!("  {} = icmp ne i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::Less => format!("  {} = icmp slt i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::LessEqual => format!("  {} = icmp sle i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::Greater => format!("  {} = icmp sgt i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::GreaterEqual => format!("  {} = icmp sge i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::And => format!("  {} = and i64 {}, {}", temp_reg, lhs, rhs),
                BinaryOp::Or => format!("  {} = or i64 {}, {}", temp_reg, lhs, rhs),
            };

            self.instructions.push(op_instr);
            Ok(Some(temp_reg))
        } else {
            codegen_error("Binary operation on invalid operands".to_string())
        }
    }

    /// Generate LLVM IR for unary operations
    fn generate_unary(&mut self, unary: &UnaryExpr) -> Result<Option<String>> {
        let operand = self.generate_expression(&unary.operand)?;

        match unary.operator {
            UnaryOp::Not => {
                if let Some(op) = operand {
                    let temp_reg = format!("%t{}", self.instructions.len());
                    self.instructions.push(format!("  {} = xor i64 {}, -1", temp_reg, op));
                    Ok(Some(temp_reg))
                } else {
                    codegen_error("Not operation on invalid operand".to_string())
                }
            }
            UnaryOp::Negate => {
                if let Some(op) = operand {
                    let temp_reg = format!("%t{}", self.instructions.len());
                    self.instructions.push(format!("  {} = sub i64 0, {}", temp_reg, op));
                    Ok(Some(temp_reg))
                } else {
                    codegen_error("Negate operation on invalid operand".to_string())
                }
            }
        }
    }

    /// Generate LLVM IR for function calls
    fn generate_call(&mut self, call: &CallExpr) -> Result<Option<String>> {
        // For now, assume the function is an identifier (function name)
        if let Expression::Identifier(func_name) = &*call.function {
            if self.functions.contains_key(func_name) {
                // Generate arguments
                let mut arg_strs = Vec::new();
                for arg in &call.arguments {
                    if let Some(arg_val) = self.generate_expression(arg)? {
                        arg_strs.push(arg_val);
                    } else {
                        return codegen_error("Invalid argument in function call".to_string());
                    }
                }

                let args_str = arg_strs.join(", ");
                let temp_reg = format!("%t{}", self.instructions.len());
                let call_instr = format!("  {} = call i64 @{}({})", temp_reg, func_name, args_str);
                self.instructions.push(call_instr);

                Ok(Some(temp_reg))
            } else {
                codegen_error(format!("Undefined function: {}", func_name))
            }
        } else {
            codegen_error("Complex function expressions not yet supported".to_string())
        }
    }

    /// Generate LLVM IR for if expressions
    fn generate_if(&mut self, if_expr: &IfExpr) -> Result<Option<String>> {
        let cond = self.generate_expression(&if_expr.condition)?;

        if let Some(cond_val) = cond {
            let then_label = format!("then_{}", self.instructions.len());
            let else_label = format!("else_{}", self.instructions.len());
            let end_label = format!("end_{}", self.instructions.len());

            // Generate conditional branch
            self.instructions.push(format!("  br i1 {}, label {}, label {}",
                cond_val, then_label, else_label));

            // Generate then block
            self.instructions.push(format!("{}:", then_label));
            let then_val = self.generate_expression(&if_expr.then_branch)?;
            self.instructions.push(format!("  br label {}", end_label));

            // Generate else block
            self.instructions.push(format!("{}:", else_label));
            let else_val = self.generate_expression(&if_expr.else_branch)?;
            self.instructions.push(format!("  br label {}", end_label));

            // Generate merge block with phi
            self.instructions.push(format!("{}:", end_label));
            if let (Some(then_result), Some(else_result)) = (then_val, else_val) {
                let phi_reg = format!("%t{}", self.instructions.len());
                self.instructions.push(format!("  {} = phi i64 [ {}, {} ], [ {}, {} ]",
                    phi_reg,
                    then_result, then_label,
                    else_result, else_label));
                Ok(Some(phi_reg))
            } else {
                codegen_error("If branches must have values".to_string())
            }
        } else {
            codegen_error("If condition must be valid".to_string())
        }
    }

    /// Write the generated LLVM IR to a file
    pub fn write_to_file(&self, filename: &str) -> Result<()> {
        let content = self.instructions.join("\n");
        std::fs::write(filename, content)
            .map_err(|e| CompilerError::IoError(e))
    }

    /// Print the generated LLVM IR (for debugging)
    pub fn print_ir(&self) {
        println!("Generated LLVM IR (Text Representation):");
        println!("========================================");
        for instruction in &self.instructions {
            println!("{}", instruction);
        }
    }

    /// Generate LLVM IR for memory allocation (alloc_ref)
    fn generate_alloc_ref(&mut self, alloc: &AllocRefExpr) -> Result<Option<String>> {
        // Generate region and initial value expressions
        let region_val = self.generate_expression(&alloc.region)?;
        let initial_val = self.generate_expression(&alloc.initial_value)?;

        if let (Some(region), Some(val)) = (region_val, initial_val) {
            let ref_reg = format!("%ref_{}", self.instructions.len());

            // Call Silica runtime region allocation function
            // silica_region_alloc(region_ptr, initial_value) -> ref_ptr
            self.instructions.push(format!("  {} = call i8* @silica_region_alloc({}, {})", ref_reg, region, val));

            Ok(Some(ref_reg))
        } else {
            codegen_error("Invalid region or initial value for allocation".to_string())
        }
    }

    /// Generate LLVM IR for memory read (read_ref)
    fn generate_read_ref(&mut self, read: &ReadRefExpr) -> Result<Option<String>> {
        // Generate reference expression
        let ref_val = self.generate_expression(&read.reference)?;

        if let Some(ref_ptr) = ref_val {
            // Call Silica runtime read function
            let value_reg = format!("%value_{}", self.instructions.len());
            self.instructions.push(format!("  {} = call i64 @silica_region_read({})", value_reg, ref_ptr));
            Ok(Some(value_reg))
        } else {
            codegen_error("Invalid reference for read operation".to_string())
        }
    }

    /// Generate LLVM IR for memory write (write_ref)
    fn generate_write_ref(&mut self, write: &WriteRefExpr) -> Result<Option<String>> {
        // Generate reference and value expressions
        let ref_val = self.generate_expression(&write.reference)?;
        let value_val = self.generate_expression(&write.value)?;

        if let (Some(ref_ptr), Some(val)) = (ref_val, value_val) {
            // Call Silica runtime write function
            self.instructions.push(format!("  call void @silica_region_write({}, {})", ref_ptr, val));
            // Write operations return unit, so no result register
            Ok(None)
        } else {
            codegen_error("Invalid reference or value for write operation".to_string())
        }
    }

    /// Generate LLVM IR for actor spawn (spawn)
    fn generate_spawn(&mut self, spawn: &SpawnExpr) -> Result<Option<String>> {
        // Generate initial state and behavior expressions
        let initial_state = self.generate_expression(&spawn.initial_state)?;
        let behavior = self.generate_expression(&spawn.behavior)?;

        if let (Some(state), Some(behav)) = (initial_state, behavior) {
            let actor_reg = format!("%actor_{}", self.instructions.len());

            // Call Silica runtime actor spawn function
            // silica_actor_spawn(initial_state, behavior_fn) -> actor_ref
            self.instructions.push(format!("  {} = call i8* @silica_actor_spawn({}, {})", actor_reg, state, behav));

            Ok(Some(actor_reg))
        } else {
            codegen_error("Invalid initial state or behavior for spawn".to_string())
        }
    }

    /// Generate LLVM IR for message send (send)
    fn generate_send(&mut self, send: &SendExpr) -> Result<Option<String>> {
        // Generate actor and message expressions
        let actor = self.generate_expression(&send.actor)?;
        let message = self.generate_expression(&send.message)?;

        if let (Some(actor_ref), Some(msg)) = (actor, message) {
            // Call Silica runtime send function
            self.instructions.push(format!("  call void @silica_actor_send({}, {})", actor_ref, msg));

            // Send operations return unit, so no result register
            Ok(None)
        } else {
            codegen_error("Invalid actor or message for send".to_string())
        }
    }

    /// Generate LLVM IR for message receive (recv)
    fn generate_recv(&mut self, _recv: &RecvExpr) -> Result<Option<String>> {
        // Call Silica runtime receive function
        let msg_reg = format!("%msg_{}", self.instructions.len());
        self.instructions.push(format!("  {} = call i64 @silica_actor_recv()", msg_reg));

        Ok(Some(msg_reg))
    }
}

/// Type mapping between Silica types and LLVM types (string representation)
pub struct TypeMap {}

impl TypeMap {
    pub fn new() -> Self {
        TypeMap {}
    }

    /// Run optimization passes on the generated code
    #[cfg(feature = "llvm_backend")]
    pub fn optimize_module(&self, module: &inkwell::module::Module) -> Result<()> {
        match self.optimization_level {
            OptimizationLevel::None => {
                // No optimizations
                Ok(())
            }
            OptimizationLevel::Basic => {
                self.run_basic_optimizations(module)
            }
            OptimizationLevel::Standard => {
                self.run_standard_optimizations(module)
            }
            OptimizationLevel::Aggressive => {
                self.run_aggressive_optimizations(module)
            }
        }
    }

    #[cfg(feature = "llvm_backend")]
    fn run_basic_optimizations(&self, module: &inkwell::module::Module) -> Result<()> {
        // Create function pass manager for basic optimizations
        let fpm = PassManager::create_function(module);

        // Add basic optimization passes
        fpm.add_constant_merge_pass();
        fpm.add_dead_store_elimination_pass();
        fpm.add_instruction_combining_pass();
        fpm.add_reassociate_pass();
        fpm.add_gvn_pass();
        fpm.add_cfg_simplification_pass();

        // Run passes on all functions
        for function in module.get_functions() {
            fpm.run_on(&function);
        }

        Ok(())
    }

    #[cfg(feature = "llvm_backend")]
    fn run_standard_optimizations(&self, module: &inkwell::module::Module) -> Result<()> {
        // Create function pass manager for standard optimizations
        let fpm = PassManager::create_function(module);

        // Add comprehensive optimization passes
        fpm.add_constant_merge_pass();
        fpm.add_dead_store_elimination_pass();
        fpm.add_instruction_combining_pass();
        fpm.add_reassociate_pass();
        fpm.add_gvn_pass();
        fpm.add_cfg_simplification_pass();
        fpm.add_basic_alias_analysis_pass();
        fpm.add_promote_memory_to_register_pass();
        fpm.add_instruction_simplifier_pass();
        fpm.add_tail_call_elimination_pass();

        // Run passes on all functions
        for function in module.get_functions() {
            fpm.run_on(&function);
        }

        Ok(())
    }

    #[cfg(feature = "llvm_backend")]
    fn run_aggressive_optimizations(&self, module: &inkwell::module::Module) -> Result<()> {
        // Create function pass manager for aggressive optimizations
        let fpm = PassManager::create_function(module);

        // Add aggressive optimization passes (may increase compile time)
        fpm.add_constant_merge_pass();
        fpm.add_dead_store_elimination_pass();
        fpm.add_instruction_combining_pass();
        fpm.add_reassociate_pass();
        fpm.add_gvn_pass();
        fpm.add_cfg_simplification_pass();
        fpm.add_basic_alias_analysis_pass();
        fpm.add_promote_memory_to_register_pass();
        fpm.add_instruction_simplifier_pass();
        fpm.add_tail_call_elimination_pass();
        fpm.add_loop_rotate_pass();
        fpm.add_loop_unroll_pass();
        fpm.add_loop_unswitch_pass();

        // Run passes on all functions
        for function in module.get_functions() {
            fpm.run_on(&function);
        }

        Ok(())
    }


    /// Convert Silica type to LLVM type string representation
    pub fn silica_to_llvm_str(&self, silica_type: &Type) -> String {
        match silica_type {
            Type::Unit => "void".to_string(),
            Type::Bool => "i1".to_string(),
            Type::Int => "i64".to_string(),
            Type::Char => "i32".to_string(),
            Type::String => "i8*".to_string(),
            Type::Function { .. } => "i8*".to_string(), // Function pointers as void*
            Type::Tuple(_) => "i8*".to_string(), // Structs as opaque pointers
            Type::Record(_) => "i8*".to_string(),
            Type::Variant(_) => "i8*".to_string(),
            Type::Process { .. } => "i8*".to_string(),
            Type::Region { .. } => "i8*".to_string(),
            Type::Reference { .. } => "i64*".to_string(),
            Type::Buffer { .. } => "i8*".to_string(),
            Type::ActorRef { .. } => "i8*".to_string(),
            Type::Variable(_) => "i64".to_string(),
            Type::Named(_) => "i64".to_string(),
            Type::Generic { .. } => "i8*".to_string(), // Generic types as opaque pointers
        }
    }
}

